# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: install Angular
    init: npm install -g @angular/cli # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: cd myapp && ng serve --disable-host-check

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
#ports:
 # - name: Frontend
 #  description: Port 3000 for the frontend
 #   port: 3000
 #   onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
